# ===================================
#  List Behavior Config
# ===================================

list: $/thewebsiteguy/avalanchecrm/models/subscriptionplan/columns.yaml

modelClass: TheWebsiteGuy\AvalancheCRM\Models\SubscriptionPlan

title: "Subscription Plans"

recordUrl: thewebsiteguy/avalanchecrm/subscriptionplans/update/:id

noRecordsMessage: backend::lang.list.no_records

recordsPerPage: 20

showPageNumbers: true
showSetup: true
showSorting: true
showCheckboxes: true

toolbar:
  buttons: list_toolbar
  search:
    prompt: backend::lang.list.search_prompt
