# ===================================
#  Form Behavior Config
# ===================================

name: "Subscription Plan"

form: $/thewebsiteguy/avalanchecrm/models/subscriptionplan/fields.yaml

modelClass: TheWebsiteGuy\AvalancheCRM\Models\SubscriptionPlan

defaultRedirect: thewebsiteguy/avalanchecrm/subscriptionplans

create:
  title: "New Subscription Plan"
  redirect: thewebsiteguy/avalanchecrm/subscriptionplans/update/:id
  redirectClose: thewebsiteguy/avalanchecrm/subscriptionplans

update:
  title: "Edit Subscription Plan"
  redirect: thewebsiteguy/avalanchecrm/subscriptionplans
  redirectClose: thewebsiteguy/avalanchecrm/subscriptionplans

preview:
  title: "Preview Subscription Plan"
