# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'thewebsiteguy.avalanchecrm::lang.models.subscription.label'

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/subscription/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Subscription

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/subscriptions

# Create page
create:
    title: backend::lang.form.create_title
    redirect: thewebsiteguy/avalanchecrm/subscriptions/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/subscriptions

# Update page
update:
    title: backend::lang.form.update_title
    redirect: thewebsiteguy/avalanchecrm/subscriptions
    redirectClose: thewebsiteguy/avalanchecrm/subscriptions

# Preview page
preview:
    title: backend::lang.form.preview_title
