title: Ticket Categories
list: $/thewebsiteguy/avalanchecrm/models/ticketcategory/columns.yaml
modelClass: TheWebsiteGuy\AvalancheCRM\Models\TicketCategory
recordUrl: thewebsiteguy/avalanchecrm/ticketcategories/update/:id
noRecordsMessage: "No categories found"
recordsPerPage: 20
showCheckboxes: true
toolbar:
  buttons: list_toolbar
  search:
    prompt: "Search categories..."
