name: Ticket Categories
form: $/thewebsiteguy/avalanchecrm/models/ticketcategory/fields.yaml
modelClass: TheWebsiteGuy\AvalancheCRM\Models\TicketCategory
defaultRedirect: thewebsiteguy/avalanchecrm/ticketcategories
create:
  redirect: thewebsiteguy/avalanchecrm/ticketcategories/update/:id
  redirectClose: thewebsiteguy/avalanchecrm/ticketcategories
update:
  redirect: thewebsiteguy/avalanchecrm/ticketcategories
  redirectClose: thewebsiteguy/avalanchecrm/ticketcategories
confirmDelete: "Do you really want to delete this category?"
