# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'thewebsiteguy.avalanchecrm::lang.models.ticket.label'

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/ticket/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Ticket

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/tickets

# Create page
create:
    title: backend::lang.form.create_title
    redirect: thewebsiteguy/avalanchecrm/tickets/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/tickets

# Update page
update:
    title: backend::lang.form.update_title
    redirect: thewebsiteguy/avalanchecrm/tickets
    redirectClose: thewebsiteguy/avalanchecrm/tickets

# Preview page
preview:
    title: backend::lang.form.preview_title
