# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'thewebsiteguy.avalanchecrm::lang.models.invoice.label'

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/invoice/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Invoice

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/invoices

# Create page
create:
    title: backend::lang.form.create_title
    redirect: thewebsiteguy/avalanchecrm/invoices/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/invoices

# Update page
update:
    title: backend::lang.form.update_title
    redirect: thewebsiteguy/avalanchecrm/invoices
    redirectClose: thewebsiteguy/avalanchecrm/invoices

# Preview page
preview:
    title: backend::lang.form.preview_title
