# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Staff member

# Model Form Structure
form: $/thewebsiteguy/avalanchecrm/models/staff/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Staff

# Default context
defaultContext: create

# Default redirect
defaultRedirect: thewebsiteguy/avalanchecrm/staff

# Create page
create:
  title: Create Staff
  redirect: thewebsiteguy/avalanchecrm/staff
  redirectClose: thewebsiteguy/avalanchecrm/staff

# Update page
update:
  title: Edit Staff
  redirect: thewebsiteguy/avalanchecrm/staff
  redirectClose: thewebsiteguy/avalanchecrm/staff

# Preview page
preview:
  title: Preview Staff
