# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'thewebsiteguy.avalanchecrm::lang.models.client.label'

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/client/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Client

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/clients

# Create page
create:
    title: backend::lang.form.create_title
    redirect: thewebsiteguy/avalanchecrm/clients/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/clients

# Update page
update:
    title: backend::lang.form.update_title
    redirect: thewebsiteguy/avalanchecrm/clients
    redirectClose: thewebsiteguy/avalanchecrm/clients

# Preview page
preview:
    title: backend::lang.form.preview_title
