# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Ticket Status

# Model Form Configuration
form: $/thewebsiteguy/nexuscrm/models/ticketstatus/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\NexusCRM\Models\TicketStatus

# Default redirect location
defaultRedirect: thewebsiteguy/nexuscrm/ticketstatuses

# Create page
create:
  title: Create Ticket Status
  redirect: thewebsiteguy/nexuscrm/ticketstatuses/update/:id
  redirectClose: thewebsiteguy/nexuscrm/ticketstatuses

# Update page
update:
  title: Edit Ticket Status
  redirect: thewebsiteguy/nexuscrm/ticketstatuses
  redirectClose: thewebsiteguy/nexuscrm/ticketstatuses

# Preview page
preview:
  title: Preview Ticket Status
