# ===================================
#  List Behavior Config
# ===================================

# Model List Configuration
list: $/thewebsiteguy/nexuscrm/models/tickettype/columns.yaml

# Model Class name
modelClass: TheWebsiteGuy\NexusCRM\Models\TicketType

# List Title
title: Manage Ticket Types

# Link URL for each record
recordUrl: thewebsiteguy/nexuscrm/tickettypes/update/:id

# Message to display if the list is empty
noRecordsMessage: No ticket types found.

# Records to display per page
recordsPerPage: 20

# Display checkboxes next to each record
showCheckboxes: true

# Toolbar widget configuration
toolbar:
  # Partial for toolbar buttons
  buttons: list_toolbar
  # Search widget configuration
  search:
    prompt: backend::lang.list.search_prompt
