# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Ticket Type

# Model Form Configuration
form: $/thewebsiteguy/nexuscrm/models/tickettype/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\NexusCRM\Models\TicketType

# Default redirect location
defaultRedirect: thewebsiteguy/nexuscrm/tickettypes

# Create page
create:
  title: Create Ticket Type
  redirect: thewebsiteguy/nexuscrm/tickettypes/update/:id
  redirectClose: thewebsiteguy/nexuscrm/tickettypes

# Update page
update:
  title: Edit Ticket Type
  redirect: thewebsiteguy/nexuscrm/tickettypes
  redirectClose: thewebsiteguy/nexuscrm/tickettypes

# Preview page
preview:
  title: Preview Ticket Type
