# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Task

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/task/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Task

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/tasks

# Create page
create:
  title: Create Task
  redirect: thewebsiteguy/avalanchecrm/tasks/update/:id
  redirectClose: thewebsiteguy/avalanchecrm/tasks

# Update page
update:
  title: Edit Task
  redirect: thewebsiteguy/avalanchecrm/tasks
  redirectClose: thewebsiteguy/avalanchecrm/tasks

# Preview page
preview:
  title: Preview Task
