# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'thewebsiteguy.avalanchecrm::lang.models.campaign.label'

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/campaign/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Campaign

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/campaigns

# Create page
create:
    title: backend::lang.form.create_title
    redirect: thewebsiteguy/avalanchecrm/campaigns/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/campaigns

# Update page
update:
    title: backend::lang.form.update_title
    redirect: thewebsiteguy/avalanchecrm/campaigns/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/campaigns

# Preview page
preview:
    title: backend::lang.form.preview_title
