# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'thewebsiteguy.avalanchecrm::lang.models.project.label'

# Model Form Field configuration
form: $/thewebsiteguy/avalanchecrm/models/project/fields.yaml

# Model Class name
modelClass: TheWebsiteGuy\AvalancheCRM\Models\Project

# Default redirect location
defaultRedirect: thewebsiteguy/avalanchecrm/projects

# Create page
create:
    title: backend::lang.form.create_title
    redirect: thewebsiteguy/avalanchecrm/projects/update/:id
    redirectClose: thewebsiteguy/avalanchecrm/projects

# Update page
update:
    title: backend::lang.form.update_title
    redirect: thewebsiteguy/avalanchecrm/projects
    redirectClose: thewebsiteguy/avalanchecrm/projects

# Preview page
preview:
    title: backend::lang.form.preview_title
