# ===================================
#  Relation Behavior Config
# ===================================

tasks:
  label: Task
  list: $/thewebsiteguy/avalanchecrm/models/task/columns.yaml
  form: $/thewebsiteguy/avalanchecrm/models/task/fields.yaml
  view:
    toolbarButtons: create|delete
